[project]
name = "laff-viewer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.4.2",
    "pandas>=2.3.3",
    "plotly>=6.6.0",
    "streamlit>=1.55.0",
    "tabulate>=0.10.0",
]

[tool.ruff.format]
quote-style = "preserve"